name: Download T5 Model

on:
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  download-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch transformers sentencepiece

    - name: Create model directory
      run: |
        mkdir -p ./t5-model

    - name: Download T5-base model
      run: |
        python -c "
        from transformers import T5Tokenizer, T5ForConditionalGeneration;
        tokenizer = T5Tokenizer.from_pretrained('t5-base', cache_dir='./t5-model');
        model = T5ForConditionalGeneration.from_pretrained('t5-base', cache_dir='./t5-model');"

    - name: Commit model to repository
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add ./t5-model
        git commit -m 'Add T5-base model'
        
    - name: Push changes
      env:
        TOKEN: ${{ secrets.ACTIONS_PAT }}  # Use your personal access token
      run: |
        git push https://${{ secrets.ACTIONS_PAT }}@github.com/renix-codex/formal-lang-transformer.git

